### PR TITLE
Add reset block

### PR DESCRIPTION
**Pull request by THEb0nny**
Needed a reset controller. When writing in JS, there is such a method, but not in blocks. Now it should be!

### CODE REVIEW

**Comment by THEb0nny** [comment]
@pelikhan please see changes...

**Review by pelikhan — APPROVED** [review]

**Comment by pelikhan** [comment]
@THEb0nny maybe you should fork this library and "own it"?

**Comment by THEb0nny** [comment]
> @THEb0nny maybe you should fork this library and "own it"?

What for? pxt-ev3 in extensions refers to this version...

**Comment by THEb0nny** [comment]
@pelikhan but that's why I add this extension to the project and its code remains without this change? Maybe you need to change the version in the extension?

**Pull request merged**
